// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctfvvxoefklmgwzktmve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0ZnZ2eG9lZmtsbWd3emt0bXZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzU2NDQsImV4cCI6MjA2NDExMTY0NH0.xclSCYGxlJsX2y3IM4udZttwvyhojzH0JWVeedWcsoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);